<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "project_registration"
 *
 * Auto generated by Extension Builder 2015-11-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['project_registration'] = [
    'title' => 'Project Registration',
    'description' => 'Project registration',
    'category' => 'plugin',
    'author' => 'Sebastian Iffland',
    'author_email' => 'sebastian.iffland@ecom-ex.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '7.6.19',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            't3ecom' => '',
            'ecom_toolbox' => '',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];